name: CodeCove
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.10'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - uses: Gr1N/setup-poetry@v7
    - run: poetry install

    - name: Generate coverage report
      run: poetry run coverage run -m unittest tests/*.py

    - run: poetry run coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        flags: unittests
        verbose: true